site_name: UserSource Docs
site_url: https://developer.usersource.io
copyright: 2015 UserSource.io 

theme: readthedocs

extra_css: ['themes/usersource/css/custom.css']

pages:
    - ['index.md', 'Introduction']
    - [sdk.md, Downloads, SDK]
    - [iosug.md, iOS Guides, Developer Guide]
    - [custg.md, iOS Guides, Customization Guide]
#    - [iosapi.md, iOS Guides, API Reference]
    - [androidug.md, Android Guides, Developer Guide]
    - [custg.md, Android Guides, Customization Guide]
#    - [androidapi.md, Android Guides, API Reference]
    - ['faq.md', Support, 'FAQ']

markdown_extensions: [admonition]




